# Docker
# Build a Docker image
# https://docs.microsoft.com/azure/devops/pipelines/languages/docker

trigger:
- main

resources:
- repo: self

stages:
- stage: Build
  displayName: Build image
  jobs:
  - job: Build
    displayName: Build
    pool:
      vmImage: ubuntu-latest
    steps:
    - task: DockerCompose@0
      displayName: Build an image
      inputs:
        action: Build services
        #azureSubscriptionEndpoint: $(azureSubscriptionEndpoint)
        dockerComposeFile: docker-compose.yml
        projectName: $(Build.Repository.Name)
        additionalImageTags: $(Build.BuildId)
    - task: DockerCompose@0
      displayName: Push services
      inputs:
        action: Push services
        dockerComposeFile: docker-compose.yml
        projectName: $(Build.Repository.Name)
        additionalImageTags: $(Build.BuildId)
